[settings]
idiomatic_version_file_enable_tools = ["node", "pnpm", "java"]

[tools]
node = "24.18.0"
pnpm = "11.5.3"
python = "3.14.5"
go = "1.24"
rust = "1.89"
java = ["21", "zulu-8", "25"]
bat = "0.26.1"
eza = "0.23.5"
fastfetch = "2.66.0"
fd = "10.4.2"
fzf = "0.74.2"
glab = "1.111.0"
jbang = "0.141.0"
jq = "1.8.2"
just = "1.57.0"
opencode = "1.18.11"
pandoc = "3.10.1"
rclone = "1.75.0"
ripgrep = "15.2.0"
sd = "1.1.0"
starship = "1.26.0"
task = "3.50.0"
tlrc = "1.13.1"
uv = "0.12.1"
watchexec = "2.5.1"
xh = "0.26.2"
yazi = "26.5.6"
yq = "4.53.3"
zoxide = "0.10.0"
"npm:@bitkyc08/opencodex" = "2.7.42"
"npm:@larksuite/cli" = "1.0.78"
maven = "3.9.16"